### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by pt8o** [justinmc/react-audio-player#100]
I've got a React Audio Player doing this:

```
onLoadedMetadata={e => {
  onSetDuration(e.currentTarget.duration);
}}
```

It works but TypeScript complains that `duration` doesn't exist on `e.currentTarget`.

Currently all of the events are being typed as `Event`. The [DefinitelyTyped entry](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-audio-player/index.d.ts) types the events as ` React.SyntheticEvent<HTMLAudioElement, Event>`. This is probably more accurate right?

**Comment by Michael-Gatmaitan** [comment]
Use "onDurationChange" intead of "onLoadedMetaData" for changing duration state.
