### ISSUE TITLE
Unregister event listeners on unmount

### ISSUE THREAD

**Issue by emibcn** [justinmc/react-audio-player#104]
When unmounting this component, some events are still fired.

### Solution

Clean side effects related to DOM event listeners:
- Create instance methods so they remain unchanged for the `removeEventListener` call
- Add `componentWillUnmount` with all the `removeEventListener` calls

**Comment by emibcn** [comment]
Duplicate of https://github.com/justinmc/react-audio-player/issues/57

**Comment by justinmc** [comment]
Closing with https://github.com/justinmc/react-audio-player/pull/105
