### ISSUE TITLE
React Peer Dependency Issue

### ISSUE THREAD

**Issue by nickw444** [justinmc/react-audio-player#14]
```
npm ERR! peerinvalid Peer react-audio-player@0.3.0 wants react@^15.0.2
```

The latest version of react is `15.4.1`, and this is causing NPM to be unhappy.

**Comment by justinmc** [comment]
Thanks for this, fail on my part!  This should be fixed with https://github.com/justinmc/react-audio-player/pull/15, sorry it took so long to get out.
