### ISSUE TITLE
Add 'loadedmetadata' handler.

### ISSUE THREAD

**Issue by andremalkine** [justinmc/react-audio-player#28]
Just a suggestion. It's possible to wait for 'canplay' or 'canplaythrough', but when making custom controls getting the duration of the targeted track as soon as possible is nice.

**Comment by justinmc** [comment]
@andremalkine Thanks for the suggestion.  What do you think of something like `onDurationChange` that ties to the html element's [durationchange event](https://developer.mozilla.org/en-US/docs/Web/Events/durationchange)?

There are a few native audio tag features like this that I still want to create a nice wrapper for at some point.  Let me know if that would handle your use case and I'll go ahead and write a PR.

**Comment by egdbear** [comment]
[#37](https://github.com/justinmc/react-audio-player/pull/37)

**Comment by justinmc** [comment]
Closing with https://github.com/justinmc/react-audio-player/pull/37
