### ISSUE TITLE
Example app error, missing loop in props validation

### ISSUE THREAD

**Issue by jklegseth** [justinmc/react-audio-player#29]
Running `npm run example` I get an error:

```
ERROR in ./src/index.jsx

/Applications/MAMP/htdocs/sandbox/react-audio-player/src/index.jsx
  103:26  error  'loop' is missing in props validation  react/prop-types
```

Fixed it by adding it to `ReactAudioPlayer.propTypes`:

```
ReactAudioPlayer.propTypes = {
  loop: React.PropTypes.bool,
  ...
```

**Comment by justinmc** [comment]
@jklegseth Thanks and sorry for the late reply!  I just published a new release that includes your fix: https://github.com/justinmc/react-audio-player/releases/tag/v0.4.1
