### ISSUE TITLE
Deprecation warnings when using this library with React 15.5.*

### ISSUE THREAD

**Issue by pkosiec** [justinmc/react-audio-player#31]
Due to `React.PropTypes` deprecation and react-unknown-props, those warnings occurs when using react-audio-player component.

<img width="1435" alt="screen shot 2017-04-23 at 14 46 17" src="https://cloud.githubusercontent.com/assets/7155799/25313703/180413d6-2834-11e7-91b4-66e5f5b34cd0.png">

**Comment by justinmc** [comment]
The first warning pictured was fixed with https://github.com/justinmc/react-audio-player/issues/30, but the second one I plan to fix with a permanent solution in another PR.

**Comment by justinmc** [comment]
The `Unknown props` error should no longer happen with https://github.com/justinmc/react-audio-player/pull/32 released in v0.5.0, and above.  Let me know if you ever see either of these show up again though!
