### ISSUE TITLE
TransformError - Unknown Plugin - React-Hot-Loader/Babel

### ISSUE THREAD

**Issue by allenweiss** [justinmc/react-audio-player#34]
I added the react audio player using npm today. All I get when I go to the screen where this is imported is a message that says:

TransformError: at react-audio-player/dist/bundle.js: Unknown plugin "react-hot-loader/babel" specified in react-audio-player/.babelrc at 0

I have react-hot-loader installed.

**Comment by justinmc** [comment]
Hmm, not sure why that plugin would cause a problem when installed in a separate project.  It should be using the version that's already compiled.

If you search in the actual source code that you have installed (`node_modules/react-audio-player/dist/bundle.js`), is there any mention of `react-hot-loader/babel` like the error says?  There shouldn't be.  Also let me know what version you've got installed.

Another thing to try might be to clone this project and try running the example (`npm install` then `npm run example`) and make sure that works as you'd expect.

Let me know what you see.  I definitely want to resolve any setup issues people might have so I'm happy to work through this with you.

**Comment by allenweiss** [comment]
It looks like the problem is that I'm running this using Expo, which apparently doesn't allow using native libs...sorry about asking the question.

**Comment by justinmc** [comment]
@allenweiss That makes sense, I'd guess you want a native audio player in a React Native app.  I'm going to close this, but let me know if you end up wanting to get this running still.
