### ISSUE TITLE
'Seek' not working

### ISSUE THREAD

**Issue by christianpbrink** [justinmc/react-audio-player#36]
I'm new to the project and am finding that seeking by dragging the progress indicator on the progress bar does nothing. If the audio is paused, the indicator will stay where I drop it, but only until I hit play, at which point it'll snap back to wherever it was before I dragged. If I drag while the audio is playing, the indicator just jumps snaps back right away.

I've tried with m4a, ogg, and webm files. Didn't seem to make any difference.

Any thoughts much appreciated!

**Comment by christianpbrink** [comment]
Was a problem with my server -- didn't accept byte range requests.

**Comment by justinmc** [comment]
@christianpbrink Ah that's pretty subtle, I'm glad you figured it out.  Thanks for opening this issue anyway, maybe it will save someone else with the same bug a headache.
