### ISSUE TITLE
how can i start audio play with custom button click

### ISSUE THREAD

**Issue by kalyanpkumar** [justinmc/react-audio-player#43]
i am using your wrapper.. but i want to start playing audio on my button click.. i will hide the controls... but on my button click how can i invoke audio playing?

**Comment by alfred1994** [comment]
```
<ReactAudioPlayer
  ref={(element) => { this.rap = element; }}
/>
```
`this.rap.audioEl.play()`

**Comment by kalyanpkumar** [comment]
Great.. Thanks.. that worked....

**Comment by justinmc** [comment]
Looks good.  Maybe we should add this as an example in the readme if enough people have this question.
