### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by pablonm3** [justinmc/react-audio-player#44]
The component works perfectly on desktop browsers but when i run my website on an Iphone with the last version of safari, or with an android running chrome the sounds are not being played, I am using React V16, and the version of this library is the: 0.6.4
this is the component i have for playing audio: 
`class Speaker extends Component{
   render(){  
        var play = null;  
       if(this.props.play)  
            play = (<ReactAudioPlayer  
                    src={this.props.src}  
                    autoPlay     
                    style={{display:"none"}}  
                    onEnded={this.props.onEnded}  
                    />)  
       return(  
           <span>  
                {play}  
           </span>  
       )  
   }   
}  
`

**Comment by justinmc** [comment]
Are you aware of the autoplay restrictions on mobile?  For example for Chrome: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

If you set `controls`, does it work when you hit the play button?

**Comment by pablonm3** [comment]
yeah, thanks! the component works perfectly, the problem was what you just mentioned!

**Comment by justinmc** [comment]
Cool glad that was it! I'll close this.

**Comment by woudsma** [comment]
Short question, haven't been able to test it yet; does the audio keep playing in the background when a user returns to the home screen on iPhone/Android? I'll try this out soon, i've read mixed opinions, just not sure if it's possible on e.g. iOS11.

**Comment by justinmc** [comment]
@woudsma Yes it does!  It also continues to play when the phone is locked on both Android and iOS, and can show controls and info on the lock screen.  It's just how those browsers handle the native `<audio>` tag.

I used this to write a podcast player awhile back and I think it was well suited for that kind of use case.

**Comment by woudsma** [comment]
Awesome, will give this a try soon!

**Comment by wontwon** [comment]
Hi @justinmc, for some reason I was using this plugin about 5 months ago for my project to play recorded audio messages in mp3 format. Everything worked fine before, but when I came back to update my app, the audio just stopped playing on mobile. It works just fine on desktop chrome
