### ISSUE TITLE
remove node_modules from [npm publish] directory example please!

### ISSUE THREAD

**Issue by salars** [justinmc/react-audio-player#46]
got stucked when running npm install

**Comment by justinmc** [comment]
Ah you're right, sorry about that.  I should add the whole example directory to .npmignore.  I'll do that and release a new version shortly.

**Comment by justinmc** [comment]
Done! Try this: https://github.com/justinmc/react-audio-player/releases/tag/v0.9.1

Thanks for making this issue, and let me know if this doesn't solve your problem.

**Comment by salars** [comment]
checked and ok ,good job 👍
