### ISSUE TITLE
Make crossOrigin a conditional prop

### ISSUE THREAD

**Issue by dmcmorris** [justinmc/react-audio-player#48]
As of 0.10.0, the crossOrigin param, even with anonymous set, triggers a CORS error on audio load for a standard react-scripts dev environment.  It should be made a conditional prop so that credential mode can be set to `omit`, which is what occurs without `crossorigin` set, and applicable for most, simple use cases.

**Comment by justinmc** [comment]
Thanks for the issue!  Take a look at the linked PR and let me know if that fixes the problem for your case.

Also, can you walk me through how to reproduce this?  I added react-audio-player @v0.10.0 to a brand new create react app project and didn't see any cors problems (running the app locally, accessing an external audio file).

```
        <ReactAudioPlayer
          src="https://upload.wikimedia.org/wikipedia/commons/0/08/George_Gershwin_playing_Rhapsody_in_Blue.ogg"
          controls
        />
```
