### ISSUE TITLE
Using with files with disabled CORS

### ISSUE THREAD

**Issue by jakub-zawislak** [justinmc/react-audio-player#51]
I want to play sound from Amazon S3 from bucket where I don't have access to change CORS. 

When I create `<audio>` without this library then it works

```html
<audio>
  <source src={url} type="audio/ogg"/>
</audio>
```

How I use ReactAudioPlayer:

```html
<ReactAudioPlayer src={url}/>
```

It renders:

```html
<audio class="react-audio-player " id="" preload="metadata" src="__URL__">
  <p>
    <!-- react-text: 508 -->Your browser does not support the <!-- /react-text --> 
    <code>audio</code><!-- react-text: 510 --> element.<!-- /react-text -->
  </p>
</audio>
```

Error:

> Failed to load https://s3-eu-west-1.amazonaws.com/...: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://...' is therefore not allowed access.

Is this bug or I just can't use this library without changing CORS?

**Comment by justinmc** [comment]
So sorry for forgetting about this issue 😞  I just tried uploading a public domain music file to S3 and plugging it into RAP and it works for me in Chrome, Safari, and Firefox:

```
  <ReactAudioPlayer
    src="https://s3.amazonaws.com/justinmc_test/Ketsa_-_06_-_Morning_too_Soon.mp3"
    controls
  />
```

I can't reproduce your problem, but I worry that it may be something that this project can fix...  If you're still having this problem months later, or if anyone else comes across this, feel free to post back with reproduction steps and I'll be happy to look into it.

**Comment by kkshyu** [comment]
@justinmc 
i have the same issue. 
```
Failed to load https://firebasestorage.googleapis.com/v0/b/qraft-app.appspot.com/o/videoplayback.m4a?alt=media&token=1672e0e6-776b-48dc-9fbb-5ec9c999e0a1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```
### here is my [audio](https://firebasestorage.googleapis.com/v0/b/qraft-app.appspot.com/o/videoplayback.m4a?alt=media&token=1672e0e6-776b-48dc-9fbb-5ec9c999e0a1)

here is my code
```
<ReactAudioPlayer
              src={url}
              controls={true}
            />
```
it renders
![image](https://user-images.githubusercontent.com/8722165/45329173-64a73380-b55f-11e8-82da-97a8392deef3.png)

For react audio
```
            <audio
              controls={true}
              autoPlay={active}
              onEnded={onEnded}
              onPlay={onStarted}>
              <source src={url} />
            </audio>
```
it renders
![image](https://user-images.githubusercontent.com/8722165/45329349-468e0300-b560-11e8-8b0e-f73d55938bcd.png)

i have tried to add `source` into the RAP, but still not work...
```
            <ReactAudioPlayer
              src={url}
              autoPlay={active}
              controls={true}
              onPlay={onStarted}
              onEnded={onEnded}
              preload={''}>
              <source src={url} />
            </ReactAudioPlayer>
```

**Comment by justinmc** [comment]
@kkshyu Thanks for the reproduction!

Are you using Chrome?  Are you running this locally or on a server?  Does it work if you directly render the audio tag without using RAP like you showed above?

I'm unable to reproduce it locally still!  If I use your audio file in the `src` attribute it works fine for me...

**Comment by kkshyu** [comment]
@justinmc thx for your reply

I use `create-react-app` development server and browse on Chrome. 
In the console, i will see like this:
![image](https://user-images.githubusercontent.com/8722165/45578465-202ed700-b882-11e8-85fc-db53e5051f5c.png)

i just realize the problem. It is not about RAP. Actually firebase should be setup up the `cors.json` to make js in server load the resource. Thanks for your insight!

here is the reference: https://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin/37765371#37765371

**Comment by justinmc** [comment]
@kkshyu thanks for following up and glad you got this fixed! Hopefully it will help other people with the same problem.
