### ISSUE TITLE
Remove event listeners on unmount

### ISSUE THREAD

**Issue by Secretmapper** [justinmc/react-audio-player#57]

**Comment by Reggino** [comment]
I had the same thought. But maybe this isn't required since all event listeners are installed on the `Audio`-element that will be removed automatically onunmount.

**Comment by emibcn** [comment]
> I had the same thought. But maybe this isn't required since all event listeners are installed on the Audio-element that will be removed automatically onunmount.

I have problems when unmounting, where some listeners are triggered after unmounting the `react-audio-player` component. Fixed with https://github.com/emibcn/Rac1.js/issues/15

**Comment by justinmc** [comment]
Closing now that https://github.com/justinmc/react-audio-player/pull/105 is merged, thanks!
