### ISSUE TITLE
Use function ref instead of string ref

### ISSUE THREAD

**Issue by bjackson** [justinmc/react-audio-player#6]
String refs aren't deprecated but will likely be removed in React.

https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute

**Comment by justinmc** [comment]
Thanks, I didn't realize that's where React was going with refs!  I'll make a fix later and reference it here.

**Comment by justinmc** [comment]
Fixed here! https://github.com/justinmc/react-audio-player/commit/0d4c8401322dd56d252b5a215be4139eafeb2f38
