### ISSUE TITLE
Exception occurs when user doesn't add onListen prop

### ISSUE THREAD

**Issue by bjackson** [justinmc/react-audio-player#7]
There is no check to ensure that the user has supplied an onListen function, and attempts to call it.

https://github.com/justinmc/react-audio-player/blob/master/src/index.jsx#L90

**Comment by bjackson** [comment]
Hmm. Just looked at source, and it's there...but it still occurs. Does the version in npm need to be bumped?

**Comment by justinmc** [comment]
I just bumped the npm version and republished.  Let me know if that fixes it.  Otherwise I'll try to reproduce this later.

**Comment by bjackson** [comment]
Thanks, I'll give it a try when I get home.

**Comment by justinmc** [comment]
This isn't happening for me with the latest version.  I checked the history and indeed I merged a recent PR that fixed this: https://github.com/justinmc/react-audio-player/commit/6ca06909c5a12b979a59886472c1086aaf0be5eb

Closing, but let me know if updating doesn't fix it for you.

**Comment by bjackson** [comment]
Yup, it fixed it. Thanks for the fix!!
