### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by ArielFrischer** [justinmc/react-audio-player#73]
Couldn't find typescript support for this just added a `index.d.ts` file in `node_modules/react-audio-player` with `declare module 'react-audio-player';` and that seemed to fix typescript issues.

**Comment by justinmc** [comment]
Should be coming soon in https://github.com/justinmc/react-audio-player/pull/79

**Comment by justinmc** [comment]
Supported in the latest version (v.0.13.0).
